name = "ErrorStateKalmanFilter"
uuid = "6821fe4a-5b9b-4135-a052-08d5b6714988"
authors = ["Dimitri Lozeve <dimitri@lozeve.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
